# Name of your GitHub Actions workflow
name: dbt CD Workflow (Deployment)

# -----------------
# TRIGGER
# -----------------
# This workflow ONLY runs on a push to the 'main' branch.
on:
  push:
    branches:
      - main

# -----------------
# JOBS
# -----------------
jobs:
  dbt_cd_build:
    runs-on: ubuntu-latest
    env:
      MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb==1.3.2
          pip install dbt-duckdb

      - name: Configure dbt Profile
        run: |
            mkdir -p ~/.dbt
            cat <<EOF > ~/.dbt/profiles.yml
            portfolio_project_1:
              target: prod
              outputs:
                prod:
                  type: duckdb
                  path: "md:ga4_db?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
                  schema: analytics_prod
                  threads: 4
            EOF

      - name: Install dbt packages
        run: dbt deps

      # -----------------
      # THE CRITICAL STEP
      # -----------------

      - name: Run dbt build for Production
        run: dbt build --target prod
      
      - name: Upload prod state (manifest + run_results)
        uses: actions/upload-artifact@v4
        with:
          name: prod-state
          path: |
            target/manifest.json
            target/run_results.json
          if-no-files-found: error
          retention-days: 14