name: dbt CI Workflow

on:
  push:
    branches:
      - dev
      - 'feature/**'

jobs:
  dbt_ci_build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code
      # This will now include your packages.yml file
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb==1.3.2
          pip install dbt-duckdb

      # Step 4: Configure dbt Profile
      - name: Configure dbt Profile
        run: |
            mkdir -p ~/.dbt
            cat <<EOF > ~/.dbt/profiles.yml
            portfolio_project_1:
              target: dev
              outputs:
                dev:
                  type: duckdb
                  path: "dbt_warehouse.duckdb"
            EOF
          
      # Step 5: Install dbt packages
      - name: Install dbt packages
        run: dbt deps

      # Step 6: Run dbt build
      # This command will now succeed because the dbt_utils macros are available
      - name: Run dbt build
        run: dbt build