name: dbt CI Workflow
on:
  push:
    branches:
      - dev
      - 'feature/**'

jobs:
    dbt_ci_build:
        runs-on: ubuntu-latest
    
        env:
            MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
        
        steps:
        # Step 1
        - name: Check out repository code
          uses: actions/checkout@v4
        
          # Step 2
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        
        # Step 3
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install dbt-duckdb
        
                  - name: Configure dbt Profile
        
        # Step 4
        - name: Configure dbt Profile
          run: |
            mkdir -p ~/.dbt
            cat <<EOF > ~/.dbt/profiles.yml
            portfolio_project_1:
              target: dev
              outputs:
                dev:
                  type: duckdb
                  path: "md:ga4_db?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
                  schema: analytics_dev
                  threads: 4
            EOF

        # Step 5
        - name: Install dbt packages
          run: dbt deps
        
        # Step 6
        - name: Run dbt source freshness
          run: dbt source freshness --target dev
    
        # Step 7
        - name: Run dbt build
          run: dbt build --target dev