version: 2

sources:
  - name: bronze
    description: "Source data from the GA4 ecommerce database in MotherDuck."
    schema: "{% if target.name == 'prod' %}ga4_raw{% endif %}"
    tables:
      - name: dim_items
        description: "Dimension table for items in inventory."
        {% if target.name != 'prod' %}
        external:
          location: 'ga4_data/dim/dim_items/*.parquet' 
          format: parquet 
        {% endif %}
        #config: 
          #freshness: 
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: dim_users
        description: "Dimension table for customers."
        {% if target.name != 'prod' %}
        external:
          location: 'ga4_data/dim/dim_users/*.parquet' 
          format: parquet 
        {% endif %}
        columns:
          - name: user_pseudo_id
            description: Primary key of the dim_users table
            data_tests:
              - unique
              - not_null 
        #config: 
          #freshness: 
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: fact_event_items
        description: "Fact table containing all items from events."
        {% if target.name != 'prod' %}
        external:
          location: 'ga4_data/fct/fct_event_items/*.parquet' 
          format: parquet 
        {% endif %}
        #config: 
          #freshness: 
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: fact_events
        description: "Fact table containing all events."
        {% if target.name != 'prod' %}        
        external:
          location: 'ga4_data/fct/fact_events/*.parquet' 
          format: parquet 
        {% endif %}
        columns:
          - name: event_id
            description: Primary key of the fact_events table
            data_tests:
              - unique
              - not_null
        #config: 
          #freshness: 
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
          