version: 2

sources:
  - name: bronze
    description: "Source data for GA4. Reads from local Parquet in dev/CI, and from the 'ga4_raw' schema in prod."
    schema: "{{ 'ga4_raw' if target.name == 'prod' else none }}"
    
    tables: {{ [
      {
        "name": "dim_items",
        "external": {
          "location": "ga4_data/dim/dim_items/*.parquet",
          "format": "parquet"
        }
      } if target.name != 'prod' else {
        "name": "dim_items",
        "description": "Dimension table for items in inventory."
      },
      {
        "name": "dim_users",
        "external": {
          "location": "ga4_data/dim/dim_users/*.parquet",
          "format": "parquet"
        },
        "columns": [
          {
            "name": "user_pseudo_id",
            "tests": ["unique", "not_null"]
          }
        ]
      } if target.name != 'prod' else {
        "name": "dim_users",
        "description": "Dimension table for customers.",
        "columns": [
          {
            "name": "user_pseudo_id",
            "description": "Primary key of the dim_users table",
            "tests": ["unique", "not_null"]
          }
        ]
      }
    ] if target.name != 'prod' else [
      {
        "name": "dim_items",
        "description": "Dimension table for items in inventory."
      },
      {
        "name": "dim_users", 
        "description": "Dimension table for customers.",
        "columns": [
          {
            "name": "user_pseudo_id",
            "description": "Primary key of the dim_users table",
            "tests": ["unique", "not_null"]
          }
        ]
      }
    ] }}