version: 2

sources:
  - name: ga4_ecommerce_data
    description: "Source data from the GA4 ecommerce database in MotherDuck."
    schema: ga4_raw 

    tables:
      - name: dim_items
        description: "Dimension table for items in inventory."
      - name: dim_users
        description: "Dimension table for customers."
      - name: fact_event_items
        description: "Fact table containing all items from events."
      - name: fact_events
        description: "Fact table containing all events."