version: 2

sources:
  - name: bronze
    description: "Source data for GA4"
    schema: "{{ 'ga4_raw' if target.name == 'prod' else none }}"
    
    tables:
      - name: dim_items
        description: "Dimension table for items in inventory."
        #config:
          #freshness:
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: dim_users
        description: "Dimension table for customers."
        columns:
          - name: user_pseudo_id
            description: Primary key of the dim_users table
            tests:
              - unique
              - not_null 
        #config:
          #freshness:
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: fact_event_items
        description: "Fact table containing all items from events."
        #config:
          #freshness:
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at
      - name: fact_events
        description: "Fact table containing all events."
        columns:
          - name: event_id
            description: Primary key of the fact_events table
            tests:
              - unique
              - not_null
        #config:
          #freshness:
          #  warn_after: {count: 12, period: hour}
          #  error_after: {count: 24, period: hour}
          # loaded_at_field: loaded_at