version: 2

sources:
  - name: bronze
    description: "Source data for GA4"
    schema: "{{ 'ga4_raw' if target.name == 'prod' else none }}"
    
    tables:
      - name: dim_items
        description: "Dimension table for items in inventory."
      
      - name: dim_users
        description: "Dimension table for customers."
        columns:
          - name: user_pseudo_id
            description: Primary key of the dim_users table
            tests:
              - unique
              - not_null 
      
      - name: fact_event_items
        description: "Fact table containing all items from events."
      
      - name: fact_events
        description: "Fact table containing all events."
        columns:
          - name: event_id
            description: Primary key of the fact_events table
            tests:
              - unique
              - not_null