version: 2

sources:
  - name: local_files
    description: "Source data from local Parquet files."
    database: "{{ env_var('DBT_DATABASE', 'dev') }}"
    schema: main 

    tables:
    - name: dim_items
      description: "Dimension table for items in inventory."
      external:
        location: 'C:/Users/David/my_dbt_project/ga4_data/dim/dim_items/**/*.parquet'
        format: parquet
    - name: dim_users
      description: "Dimension table for customers."
      external:
        location: 'C:/Users/David/my_dbt_project/ga4_data/dim/dim_users/**/*.parquet'
        format: parquet
    - name: fact_event_items
      description: "Fact table containing all items from events."
      external:
        location: 'C:/Users/David/my_dbt_project/ga4_data/fct/fact_event_items/*.parquet'
        format: parquet
    - name: fact_events
      description: "Fact table containing all events."
      external:
        location: 'C:/Users/David/my_dbt_project/ga4_data/fct/fact_events/*.parquet'
        format: parquet